<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10"/>
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\RasHub.Infrastructure\RasHub.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
