<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting"
                          Version="10.0.10"/>
        <PackageReference Update="coverlet.collector" Version="10.0.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\RasHub.Synchronization\RasHub.Synchronization.csproj"/>
    </ItemGroup>

</Project>
