<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\RasHub.Contracts\src\RasHub.Contracts\RasHub.Contracts.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Update="coverlet.collector" Version="10.0.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"/>
    </ItemGroup>
</Project>
